# Numpy

In [1]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.

Retrieving notices: ...working... done

Note: you may need to restart the kernel to use updated packages.




==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda




In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

[1 2 3 4]


In [4]:
import numpy as np

a = np.array([1,2,3])

In [5]:
a

array([1, 2, 3])

In [6]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [8]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
print(np.arange(4))
print(np.arange(0,10,2)) 

[0 1 2 3]
[0 2 4 6 8]


In [10]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

# Add , Remove , and Sort

In [11]:
arr = np.array([1,2,3,4,5,6,7,8])

In [12]:
np.append(arr,[1,2]) 

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [13]:
np.delete(arr,1)

array([1, 3, 4, 5, 6, 7, 8])

In [14]:
arr = np.array([2,1,5,3,7,4,6,8])

In [15]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

# Shape and Size

In [16]:
array_example = np.array ([[[0,1,2,3],
                            [4,5,6,7]],
                            [[0,1,2,3],
                             [4,5,6,7]],
                             [[0,1,2,3],
                              [4,5,6,7]]])
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [17]:
array_example.ndim 

3

In [18]:
array_example.size

24

In [19]:
array_example.shape 

(3, 2, 4)

In [20]:
arr_one = np.array([[1,2,3,4,5]])

In [21]:
arr_one.ndim

2

In [22]:
arr_one.size

5

In [23]:
arr_one.shape

(1, 5)

# Reshape

In [24]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [25]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [26]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Convert 1D to 2D

In [27]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [28]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [29]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [30]:
col_vector = a[: , np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [31]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [32]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [33]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Index and Slicing

In [34]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [35]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [37]:
five_up = (a >= 5)
print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [38]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [39]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


# Creating Array from Existing Data

In [40]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [41]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [42]:
a_1 = np.array([[1,1],
                [2,2]])

In [43]:
a_2 = np.array([[3,3],
                [4,4]])

In [44]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [45]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [46]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12],
       [13,14,15,16,17,18,19,20,21,22,23,24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [47]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [48]:
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [49]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [50]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic Array operation

In [51]:
a = np.array([1,2,3,4])

a.sum()

10

In [52]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [53]:
b.sum(axis=0)

array([3, 3])

In [54]:
b.sum(axis=1)

array([2, 4])

In [55]:
data = np.array([1,2])
data

array([1, 2])

In [56]:
ones = np.ones(2)
ones

array([1., 1.])

In [57]:
data + ones

array([2., 3.])

In [58]:
data * data

array([1, 4])

In [59]:
data / data

array([1., 1.])

# Broadcasting

In [60]:
data *2

array([2, 4])

In [61]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [62]:
A.sum()

4.8595784

In [63]:
A.min()

0.05093587

In [64]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [65]:
A.max()

0.82485143

In [66]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [67]:
A.std()

0.21392120766089617

Creatung Matrices

In [68]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.15091909, 0.95243959],
       [0.70918876, 0.50323844],
       [0.47119549, 0.11944988]])

In [69]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.15720768 0.60856653]
 [0.9950006  0.66376637]
 [0.12359894 0.13775381]]


# Matrix Arithmetic

In [70]:
data = np.array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


In [71]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [72]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [73]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [74]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


# Dot Product

In [75]:
a_1 = np.array([[1,2,3],
                [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8],
                [9,10],
                [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [76]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [77]:
data = np.array([[1,2],
                 [3,4],
                 [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


# Matrix Aggregation

In [78]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [79]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [80]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


# Transporting and Reshaping

In [81]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [82]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [83]:
data_col = np.array([[1,2,3,4,5,6]]) . T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [84]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [86]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


# N-Dimensional Array

In [87]:
ndarr = np.array([[[1,2], [3,4]],
                  [[5,6],[7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [88]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [89]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [90]:
print(np.random.random((4,3,2)))

[[[0.80794497 0.11013804]
  [0.81213763 0.23238937]
  [0.13019054 0.57276249]]

 [[0.14447202 0.21062681]
  [0.64745209 0.34120282]
  [0.20472674 0.67703632]]

 [[0.33374898 0.72056808]
  [0.24847007 0.71148276]
  [0.60983725 0.52784797]]

 [[0.77464934 0.11055262]
  [0.92008991 0.9811063 ]
  [0.84378361 0.2861861 ]]]


# Flatten N-Dimensional Array

In [91]:
arrflat = np.array([[1,2,3,4],
                      [5,6,7,8,],
                      [9,10,11,12]])
print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [92]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Notes on Numpy Vector

In [93]:
import numpy as np
a = np.random.rand(5)

In [94]:
print(a)

[0.86836159 0.38078823 0.82279558 0.12325048 0.49003093]


In [95]:
a.shape 

(5,)

In [96]:
print(a.T)

[0.86836159 0.38078823 0.82279558 0.12325048 0.49003093]


In [97]:
print(np.dot(a, a.T))

1.8313650837211204


In [98]:
a = np.random.rand(5,1) # Column Vector

In [99]:
print(a)

[[0.47071566]
 [0.63074853]
 [0.30524176]
 [0.08650983]
 [0.83468706]]


In [100]:
print(a.T)

[[0.47071566 0.63074853 0.30524176 0.08650983 0.83468706]]


In [101]:
print(np.dot(a, a.T))

[[0.22157323 0.29690321 0.14368207 0.04072153 0.39290027]
 [0.29690321 0.39784371 0.19253079 0.05456595 0.52647764]
 [0.14368207 0.19253079 0.09317253 0.02640641 0.25478135]
 [0.04072153 0.05456595 0.02640641 0.00748395 0.07220863]
 [0.39290027 0.52647764 0.25478135 0.07220863 0.6967025 ]]


In [102]:
a = np.random.rand(1,5) 

In [103]:
print(a)

[[0.603916   0.04433716 0.87967542 0.4063437  0.83904898]]
